package com.polban.JadwalHarianLang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_StatusEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_StatusEnum() {
    super(0xb20407ef9294e8eL, 0x8050ea856559a353L, 0x44f57300c50f6a8dL, "StatusEnum", "r:bbad0a15-3ad2-4910-b66b-8abe2a259462(com.polban.JadwalHarianLang.structure)/4969004211016526477");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_BELUM_MULAI_0 = new EnumerationDescriptor.MemberDescriptor("BELUM_MULAI", "BELUM_MULAI", 0x44f57300c50f6a8eL, "r:bbad0a15-3ad2-4910-b66b-8abe2a259462(com.polban.JadwalHarianLang.structure)/4969004211016526478");
  private final EnumerationDescriptor.MemberDescriptor myMember_BERJALAN_0 = new EnumerationDescriptor.MemberDescriptor("BERJALAN", "BERJALAN", 0x44f57300c50f6a91L, "r:bbad0a15-3ad2-4910-b66b-8abe2a259462(com.polban.JadwalHarianLang.structure)/4969004211016526481");
  private final EnumerationDescriptor.MemberDescriptor myMember_SELESAI_0 = new EnumerationDescriptor.MemberDescriptor("SELESAI", "SELESAI", 0x44f57300c50f6a92L, "r:bbad0a15-3ad2-4910-b66b-8abe2a259462(com.polban.JadwalHarianLang.structure)/4969004211016526482");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xb20407ef9294e8eL, 0x8050ea856559a353L, 0x44f57300c50f6a8dL, 0x44f57300c50f6a8eL, 0x44f57300c50f6a91L, 0x44f57300c50f6a92L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList0(myIndex, myMember_BELUM_MULAI_0, myMember_BERJALAN_0, myMember_SELESAI_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_BELUM_MULAI_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "BELUM_MULAI":
        return myMember_BELUM_MULAI_0;
      case "BERJALAN":
        return myMember_BERJALAN_0;
      case "SELESAI":
        return myMember_SELESAI_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
