package com.polban.JadwalHarianLang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_KategoriEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_KategoriEnum() {
    super(0xb20407ef9294e8eL, 0x8050ea856559a353L, 0x6524737da1e10aedL, "KategoriEnum", "r:bbad0a15-3ad2-4910-b66b-8abe2a259462(com.polban.JadwalHarianLang.structure)/7288077080416291565");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_AKADEMIK_0 = new EnumerationDescriptor.MemberDescriptor("AKADEMIK", "AKADEMIK", 0x6524737da1e10aeeL, "r:bbad0a15-3ad2-4910-b66b-8abe2a259462(com.polban.JadwalHarianLang.structure)/7288077080416291566");
  private final EnumerationDescriptor.MemberDescriptor myMember_ORGANISASI_0 = new EnumerationDescriptor.MemberDescriptor("ORGANISASI", "ORGANISASI", 0x6524737da1e10af0L, "r:bbad0a15-3ad2-4910-b66b-8abe2a259462(com.polban.JadwalHarianLang.structure)/7288077080416291568");
  private final EnumerationDescriptor.MemberDescriptor myMember_PERSONAL_0 = new EnumerationDescriptor.MemberDescriptor("PERSONAL", "PERSONAL", 0x6524737da1e10af1L, "r:bbad0a15-3ad2-4910-b66b-8abe2a259462(com.polban.JadwalHarianLang.structure)/7288077080416291569");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xb20407ef9294e8eL, 0x8050ea856559a353L, 0x6524737da1e10aedL, 0x6524737da1e10aeeL, 0x6524737da1e10af0L, 0x6524737da1e10af1L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList0(myIndex, myMember_AKADEMIK_0, myMember_ORGANISASI_0, myMember_PERSONAL_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "AKADEMIK":
        return myMember_AKADEMIK_0;
      case "ORGANISASI":
        return myMember_ORGANISASI_0;
      case "PERSONAL":
        return myMember_PERSONAL_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
