package com.polban.JadwalHarianLang.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Jadwal = 0;
  public static final int Kegiatan = 1;
  public static final int Program = 2;
  public static final int PropertiKategori = 3;
  public static final int PropertiLokasi = 4;
  public static final int PropertiStatus = 5;
  public static final int PropertiWaktu = 6;
  public static final int Tanggal = 7;
  public static final int Waktu = 8;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xb20407ef9294e8eL, 0x8050ea856559a353L);
    builder.put(0x44f57300c50f6ddbL, Jadwal);
    builder.put(0x44f57300c50f6a97L, Kegiatan);
    builder.put(0x44f57300c50f6a94L, Program);
    builder.put(0x6524737da1e256a3L, PropertiKategori);
    builder.put(0x44f57300c50f6aa1L, PropertiLokasi);
    builder.put(0x44f57300c50f6a9fL, PropertiStatus);
    builder.put(0x44f57300c50f6a9cL, PropertiWaktu);
    builder.put(0x6524737da1e5655eL, Tanggal);
    builder.put(0x6524737da1e5653eL, Waktu);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
