package com.polban.JadwalHarianLang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptJadwal = createDescriptorForJadwal();
  /*package*/ final ConceptDescriptor myConceptKegiatan = createDescriptorForKegiatan();
  /*package*/ final ConceptDescriptor myConceptProgram = createDescriptorForProgram();
  /*package*/ final ConceptDescriptor myConceptPropertiKategori = createDescriptorForPropertiKategori();
  /*package*/ final ConceptDescriptor myConceptPropertiLokasi = createDescriptorForPropertiLokasi();
  /*package*/ final ConceptDescriptor myConceptPropertiStatus = createDescriptorForPropertiStatus();
  /*package*/ final ConceptDescriptor myConceptPropertiWaktu = createDescriptorForPropertiWaktu();
  /*package*/ final EnumerationDescriptor myEnumerationKategoriEnum = new EnumerationDescriptor_KategoriEnum();
  /*package*/ final EnumerationDescriptor myEnumerationStatusEnum = new EnumerationDescriptor_StatusEnum();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptJadwal, myConceptKegiatan, myConceptProgram, myConceptPropertiKategori, myConceptPropertiLokasi, myConceptPropertiStatus, myConceptPropertiWaktu);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Jadwal:
        return myConceptJadwal;
      case LanguageConceptSwitch.Kegiatan:
        return myConceptKegiatan;
      case LanguageConceptSwitch.Program:
        return myConceptProgram;
      case LanguageConceptSwitch.PropertiKategori:
        return myConceptPropertiKategori;
      case LanguageConceptSwitch.PropertiLokasi:
        return myConceptPropertiLokasi;
      case LanguageConceptSwitch.PropertiStatus:
        return myConceptPropertiStatus;
      case LanguageConceptSwitch.PropertiWaktu:
        return myConceptPropertiWaktu;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationKategoriEnum, myEnumerationStatusEnum);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForJadwal() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.polban.JadwalHarianLang", "Jadwal", 0xb20407ef9294e8eL, 0x8050ea856559a353L, 0x44f57300c50f6ddbL);
    b.class_(false, false, false);
    b.origin("r:bbad0a15-3ad2-4910-b66b-8abe2a259462(com.polban.JadwalHarianLang.structure)/4969004211016527323");
    b.version(3);
    b.property("tanggal", 0x44f57300c50f6ddcL).type(PrimitiveTypeId.STRING).origin("4969004211016527324").done();
    b.aggregate("kegiatans", 0x44f57300c50f6dddL).target(0xb20407ef9294e8eL, 0x8050ea856559a353L, 0x44f57300c50f6a97L).optional(false).ordered(true).multiple(true).origin("4969004211016527325").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForKegiatan() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.polban.JadwalHarianLang", "Kegiatan", 0xb20407ef9294e8eL, 0x8050ea856559a353L, 0x44f57300c50f6a97L);
    b.class_(false, false, false);
    b.origin("r:bbad0a15-3ad2-4910-b66b-8abe2a259462(com.polban.JadwalHarianLang.structure)/4969004211016526487");
    b.version(3);
    b.property("name", 0x44f57300c50f6a98L).type(PrimitiveTypeId.STRING).origin("4969004211016526488").done();
    b.aggregate("waktu", 0x44f57300c50f6a99L).target(0xb20407ef9294e8eL, 0x8050ea856559a353L, 0x44f57300c50f6a9cL).optional(false).ordered(true).multiple(false).origin("4969004211016526489").done();
    b.aggregate("status", 0x44f57300c50f6a9aL).target(0xb20407ef9294e8eL, 0x8050ea856559a353L, 0x44f57300c50f6a9fL).optional(false).ordered(true).multiple(false).origin("4969004211016526490").done();
    b.aggregate("lokasi", 0x44f57300c50f6a9bL).target(0xb20407ef9294e8eL, 0x8050ea856559a353L, 0x44f57300c50f6aa1L).optional(true).ordered(true).multiple(false).origin("4969004211016526491").done();
    b.aggregate("kategori", 0x6524737da1e256a5L).target(0xb20407ef9294e8eL, 0x8050ea856559a353L, 0x6524737da1e256a3L).optional(true).ordered(true).multiple(false).origin("7288077080416376485").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForProgram() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.polban.JadwalHarianLang", "Program", 0xb20407ef9294e8eL, 0x8050ea856559a353L, 0x44f57300c50f6a94L);
    b.class_(false, false, true);
    b.origin("r:bbad0a15-3ad2-4910-b66b-8abe2a259462(com.polban.JadwalHarianLang.structure)/4969004211016526484");
    b.version(3);
    b.aggregate("jadwals", 0x44f57300c50f6a95L).target(0xb20407ef9294e8eL, 0x8050ea856559a353L, 0x44f57300c50f6ddbL).optional(false).ordered(true).multiple(true).origin("4969004211016526485").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPropertiKategori() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.polban.JadwalHarianLang", "PropertiKategori", 0xb20407ef9294e8eL, 0x8050ea856559a353L, 0x6524737da1e256a3L);
    b.class_(false, false, false);
    b.origin("r:bbad0a15-3ad2-4910-b66b-8abe2a259462(com.polban.JadwalHarianLang.structure)/7288077080416376483");
    b.version(3);
    b.property("valk", 0x6524737da1e256a4L).type(MetaIdFactory.dataTypeId(0xb20407ef9294e8eL, 0x8050ea856559a353L, 0x6524737da1e10aedL)).origin("7288077080416376484").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPropertiLokasi() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.polban.JadwalHarianLang", "PropertiLokasi", 0xb20407ef9294e8eL, 0x8050ea856559a353L, 0x44f57300c50f6aa1L);
    b.class_(false, false, false);
    b.origin("r:bbad0a15-3ad2-4910-b66b-8abe2a259462(com.polban.JadwalHarianLang.structure)/4969004211016526497");
    b.version(3);
    b.property("namaLokasi", 0x44f57300c50f6aa3L).type(PrimitiveTypeId.STRING).origin("4969004211016526499").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPropertiStatus() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.polban.JadwalHarianLang", "PropertiStatus", 0xb20407ef9294e8eL, 0x8050ea856559a353L, 0x44f57300c50f6a9fL);
    b.class_(false, false, false);
    b.origin("r:bbad0a15-3ad2-4910-b66b-8abe2a259462(com.polban.JadwalHarianLang.structure)/4969004211016526495");
    b.version(3);
    b.property("value", 0x44f57300c50f6aa0L).type(MetaIdFactory.dataTypeId(0xb20407ef9294e8eL, 0x8050ea856559a353L, 0x44f57300c50f6a8dL)).origin("4969004211016526496").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPropertiWaktu() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.polban.JadwalHarianLang", "PropertiWaktu", 0xb20407ef9294e8eL, 0x8050ea856559a353L, 0x44f57300c50f6a9cL);
    b.class_(false, false, false);
    b.origin("r:bbad0a15-3ad2-4910-b66b-8abe2a259462(com.polban.JadwalHarianLang.structure)/4969004211016526492");
    b.version(3);
    b.property("waktuMulai", 0x44f57300c50f6a9dL).type(PrimitiveTypeId.STRING).origin("4969004211016526493").done();
    b.property("waktuSelesai", 0x44f57300c50f6a9eL).type(PrimitiveTypeId.STRING).origin("4969004211016526494").done();
    return b.create();
  }
}
