package com.polban.JadwalHarianLang.sandbox;

/*Generated by MPS */


public class hehehehs {
  public static void main(String[] args) {    {
      System.out.print("Tanggal: ");      {
        System.out.println("10" + "12" + "2023");
      }

      System.out.print("Kegiatan: ");      {
        System.out.println("Makan");        {
          System.out.print("Waktu Mulai: ");          {
            System.out.println("10" + "10");
          }

          System.out.print("Waktu Selesai: ");          {
            System.out.println("12" + "0");
          }

        }

        System.out.print("Status: ");        {
          System.out.println("BELUM_MULAI");
        }

        System.out.print("Lokasi: ");        {
          System.out.println("Polban");
        }

        System.out.print("Kategori: ");        {
          System.out.println("PERSONAL");
        }

      }

    }

  }
}
