package com.polban.JadwalHarianLang.sandbox;

/*Generated by MPS */


public class ProgramToText {
  public static void main(String[] args) {    {
      System.out.println("Tanggal: ");      {
        System.out.println("10" + "12" + "2023");
      }

      System.out.println("Kegiatan: ");      {
        System.out.println("Makan");
        System.out.println("Waktu: ");        {
          System.out.println("Waktu Mulai: ");          {
            System.out.println("10" + "10");
          }

          System.out.println("Waktu Selesai: ");          {
            System.out.println("12" + "0");
          }

        }

        System.out.println("Status: ");        {
          System.out.println("BELUM_MULAI");
        }

        System.out.println("Lokasi: ");        {
          System.out.println("Polban");
        }

        System.out.println("Kategori: ");        {
          System.out.println("PERSONAL");
        }

      }

    }

  }
}
