package com.polban.JadwalHarianLang.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Jadwal_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Kegiatan_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Program_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new PropertiKategori_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new PropertiLokasi_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new PropertiStatus_Editor());
      case 6:
        return Collections.<ConceptEditor>singletonList(new PropertiWaktu_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xb20407ef9294e8eL, 0x8050ea856559a353L, 0x44f57300c50f6ddbL), MetaIdFactory.conceptId(0xb20407ef9294e8eL, 0x8050ea856559a353L, 0x44f57300c50f6a97L), MetaIdFactory.conceptId(0xb20407ef9294e8eL, 0x8050ea856559a353L, 0x44f57300c50f6a94L), MetaIdFactory.conceptId(0xb20407ef9294e8eL, 0x8050ea856559a353L, 0x6524737da1e256a3L), MetaIdFactory.conceptId(0xb20407ef9294e8eL, 0x8050ea856559a353L, 0x44f57300c50f6aa1L), MetaIdFactory.conceptId(0xb20407ef9294e8eL, 0x8050ea856559a353L, 0x44f57300c50f6a9fL), MetaIdFactory.conceptId(0xb20407ef9294e8eL, 0x8050ea856559a353L, 0x44f57300c50f6a9cL)).seal();
}
